apiVersion: apps/v1
kind: Deployment
metadata:
  name: ks8
  labels:
    app: ks8
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ks8
  template:
    metadata:
      labels:
        app: ks8
    spec:
      containers:
      - name: ks8-go
        image: vremerson/ks8:1.0
        ports:
        - containerPort: 8000

